from keyence_plc.keyence_plc_memory import PlcMemory


class AgvStatus:
    def __init__(self):
        self.AGV_ID = None
        self.POWER = None
        self.AGV_X_SPEED = None
        self.AGV_Y_SPEED = None
        self.AGV_THETA_SPEED = None
        self.AGV_FPGV = None 
        self.AGV_BPGV = None
        self.AGV_START_POINT = None
        self.AGV_END_POINT = None
        self.AGV_ACTION = None
        self.AGV_ZONE = None
        self.AGV_SLAM_X = None
        self.AGV_SLAM_Y = None
        self.AGV_SLAM_THETA = None
        self.AGV_STATUS1 = None
        self.AGV_STATUS2 = None
        self.AGV_STATUS3 = None
        self.AGV_ALARM1 = None
        self.AGV_ALARM2 = None
        self.AGV_ALARM3 = None
        self.AGV_ALARM4 = None
        self.AGV_ALARM5 = None
        self.AGV_ALARM6 = None
        self.AGV_LAYER = None
        self.AGV_ID1 = None
        self.MAGIC = None
        self.Work_id = None
        self.Robot_status = None
        self.AGV_Auto = None
        self.AGV_MOVING = None
        self.AGV_ALARM = None
        self.AGV_PATH = None
        self.AGV_PATH_REQ = None
        self.AGV_IN_MISSION = None
        self.AGV_LOCAL = None
        self.AGV_LD_COMPLETE = None
        self.AGV_UD_COMPLETE = None
        self.LOW_POWER = None
        self.MISSION_CANCEL = None
        self.TRAFFIC_STOP = None
        self.TRAFFIC_ALLOW = None
        self.PS_RETRUN = None
        self.AGV_MANUAL = None
        self.AGV_2POSITION = None
        self.IN_1 = None
        self.IN_2 = None
        self.IN_3 = None
        self.IN_4 = None
        self.IN_5 = None
        self.BARCODE_READER_FINISH = None
        self.TAG_REQ = None
        self.Req_TAGNo = None
        self.DOOR_OPEN_1 = None
        self.DOOR_CLOSE_1 = None
        self.DOOR_OPEN_2 = None
        self.DOOR_CLOSE_2 = None
        self.DOOR_OPEN_3 = None
        self.DOOR_CLOSE_3 = None
        self.DOOR_OPEN_4 = None
        self.DOOR_CLOSE_4 = None
        self.DOOR_OPEN_5 = None
        self.DOOR_CLOSE_5 = None
        self.DOOR_OPEN_6 = None
        self.DOOR_CLOSE_6 = None
        self.DOOR_OPEN_7 = None
        self.DOOR_CLOSE_7 = None
        self.DOOR_OPEN_8 = None
        self.DOOR_CLOSE_8 = None
        self.AGV_INPUT_1_1 = None
        self.AGV_INPUT_1_2 = None
        self.AGV_INPUT_1_3 = None
        self.AGV_INPUT_1_4 = None
        self.AGV_INPUT_1_5 = None
        self.AGV_INPUT_1_6 = None
        self.AGV_INPUT_1_7 = None
        self.AGV_INPUT_1_8 = None
        self.AGV_INPUT_1_9 = None
        self.AGV_INPUT_1_10 = None
        self.AGV_INPUT_1_11 = None
        self.AGV_INPUT_1_12 = None
        self.AGV_INPUT_1_13 = None
        self.AGV_INPUT_1_14 = None
        self.AGV_INPUT_1_15 = None
        self.AGV_INPUT_1_16 = None
        self.AGV_INPUT_2_1 = None
        self.AGV_INPUT_2_2 = None
        self.AGV_INPUT_2_3 = None
        self.AGV_INPUT_2_4 = None
        self.AGV_INPUT_2_5 = None
        self.AGV_INPUT_2_6 = None
        self.AGV_INPUT_2_7 = None
        self.AGV_INPUT_2_8 = None
        self.AGV_INPUT_2_9 = None
        self.AGV_INPUT_2_10 = None
        self.AGV_INPUT_2_11 = None
        self.AGV_INPUT_2_12 = None
        self.AGV_INPUT_2_13 = None
        self.AGV_INPUT_2_14 = None
        self.AGV_INPUT_2_15 = None
        self.AGV_INPUT_2_16 = None
        self.AGV_INPUT_3_1 = None
        self.AGV_INPUT_3_2 = None
        self.AGV_INPUT_3_3 = None
        self.AGV_INPUT_3_4 = None
        self.AGV_INPUT_3_5 = None
        self.AGV_INPUT_3_6 = None
        self.AGV_INPUT_3_7 = None
        self.AGV_INPUT_3_8 = None
        self.AGV_INPUT_3_9 = None
        self.AGV_INPUT_3_10 = None
        self.AGV_INPUT_3_11 = None
        self.AGV_INPUT_3_12 = None
        self.AGV_INPUT_3_13 = None
        self.AGV_INPUT_3_14 = None
        self.AGV_INPUT_3_15 = None
        self.AGV_INPUT_3_16 = None
        self.AGV_INPUT_4_1 = None
        self.AGV_INPUT_4_2 = None
        self.AGV_INPUT_4_3 = None
        self.AGV_INPUT_4_4 = None
        self.AGV_INPUT_4_5 = None
        self.AGV_INPUT_4_6 = None
        self.AGV_INPUT_4_7 = None
        self.AGV_INPUT_4_8 = None
        self.AGV_INPUT_4_9 = None
        self.AGV_INPUT_4_10 = None
        self.AGV_INPUT_4_11 = None
        self.AGV_INPUT_4_12 = None
        self.AGV_INPUT_4_13 = None
        self.AGV_INPUT_4_14 = None
        self.AGV_INPUT_4_15 = None
        self.AGV_INPUT_4_16 = None
        self.AGV_INPUT_5_1 = None
        self.AGV_INPUT_5_2 = None
        self.AGV_INPUT_5_3 = None
        self.AGV_INPUT_5_4 = None
        self.AGV_INPUT_5_5 = None
        self.AGV_INPUT_5_6 = None
        self.AGV_INPUT_5_7 = None
        self.AGV_INPUT_5_8 = None
        self.AGV_INPUT_5_9 = None
        self.AGV_INPUT_5_10 = None
        self.AGV_INPUT_5_11 = None
        self.AGV_INPUT_5_12 = None
        self.AGV_INPUT_5_13 = None
        self.AGV_INPUT_5_14 = None
        self.AGV_INPUT_5_15 = None
        self.AGV_INPUT_5_16 = None
        self.AGV_OUTPUT_1_1 = None
        self.AGV_OUTPUT_1_2 = None
        self.AGV_OUTPUT_1_3 = None
        self.AGV_OUTPUT_1_4 = None
        self.AGV_OUTPUT_1_5 = None
        self.AGV_OUTPUT_1_6 = None
        self.AGV_OUTPUT_1_7 = None
        self.AGV_OUTPUT_1_8 = None
        self.AGV_OUTPUT_1_9 = None
        self.AGV_OUTPUT_1_10 = None
        self.AGV_OUTPUT_1_11 = None
        self.AGV_OUTPUT_1_12 = None
        self.AGV_OUTPUT_1_13 = None
        self.AGV_OUTPUT_1_14 = None
        self.AGV_OUTPUT_1_15 = None
        self.AGV_OUTPUT_1_16 = None
        self.AGV_OUTPUT_2_1 = None
        self.AGV_OUTPUT_2_2 = None
        self.AGV_OUTPUT_2_3 = None
        self.AGV_OUTPUT_2_4 = None
        self.AGV_OUTPUT_2_5 = None
        self.AGV_OUTPUT_2_6 = None
        self.AGV_OUTPUT_2_7 = None
        self.AGV_OUTPUT_2_8 = None
        self.AGV_OUTPUT_2_9 = None
        self.AGV_OUTPUT_2_10 = None
        self.AGV_OUTPUT_2_11 = None
        self.AGV_OUTPUT_2_12 = None
        self.AGV_OUTPUT_2_13 = None
        self.AGV_OUTPUT_2_14 = None
        self.AGV_OUTPUT_2_15 = None
        self.AGV_OUTPUT_2_16 = None
        self.AGV_OUTPUT_3_1 = None
        self.AGV_OUTPUT_3_2 = None
        self.AGV_OUTPUT_3_3 = None
        self.AGV_OUTPUT_3_4 = None
        self.AGV_OUTPUT_3_5 = None
        self.AGV_OUTPUT_3_6 = None
        self.AGV_OUTPUT_3_7 = None
        self.AGV_OUTPUT_3_8 = None
        self.AGV_OUTPUT_3_9 = None
        self.AGV_OUTPUT_3_10 = None
        self.AGV_OUTPUT_3_11 = None
        self.AGV_OUTPUT_3_12 = None
        self.AGV_OUTPUT_3_13 = None
        self.AGV_OUTPUT_3_14 = None
        self.AGV_OUTPUT_3_15 = None
        self.AGV_OUTPUT_3_16 = None
        self.AGV_OUTPUT_4_1 = None
        self.AGV_OUTPUT_4_2 = None
        self.AGV_OUTPUT_4_3 = None
        self.AGV_OUTPUT_4_4 = None
        self.AGV_OUTPUT_4_5 = None
        self.AGV_OUTPUT_4_6 = None
        self.AGV_OUTPUT_4_7 = None
        self.AGV_OUTPUT_4_8 = None
        self.AGV_OUTPUT_4_9 = None
        self.AGV_OUTPUT_4_10 = None
        self.AGV_OUTPUT_4_11 = None
        self.AGV_OUTPUT_4_12 = None
        self.AGV_OUTPUT_4_13 = None
        self.AGV_OUTPUT_4_14 = None
        self.AGV_OUTPUT_4_15 = None
        self.AGV_OUTPUT_4_16 = None
        self.AGV_OUTPUT_5_1 = None
        self.AGV_OUTPUT_5_2 = None
        self.AGV_OUTPUT_5_3 = None
        self.AGV_OUTPUT_5_4 = None
        self.AGV_OUTPUT_5_5 = None
        self.AGV_OUTPUT_5_6 = None
        self.AGV_OUTPUT_5_7 = None
        self.AGV_OUTPUT_5_8 = None
        self.AGV_OUTPUT_5_9 = None
        self.AGV_OUTPUT_5_10 = None
        self.AGV_OUTPUT_5_11 = None
        self.AGV_OUTPUT_5_12 = None
        self.AGV_OUTPUT_5_13 = None
        self.AGV_OUTPUT_5_14 = None
        self.AGV_OUTPUT_5_15 = None
        self.AGV_OUTPUT_5_16 = None
        self.ALARM_STATUS_1 = None
        self.ALARM_STATUS_2 = None
        self.ALARM_STATUS_3 = None
        self.ALARM_STATUS_4 = None
        self.ALARM_STATUS_5 = None
        self.ALARM_STATUS_6 = None
        self.ALARM_STATUS_7 = None
        self.ALARM_STATUS_8 = None
        self.ALARM_STATUS_9 = None
        self.ALARM_STATUS_10 = None
        self.ALARM_STATUS_11 = None
        self.ALARM_STATUS_12 = None
        self.ALARM_STATUS_13 = None
        self.ALARM_STATUS_14 = None
        self.ALARM_STATUS_15 = None
        self.ALARM_STATUS_16 = None
        self.ALARM_STATUS_17 = None
        self.ALARM_STATUS_18 = None
        self.ALARM_STATUS_19 = None
        self.ALARM_STATUS_20 = None
        self.ALARM_STATUS_21 = None
        self.ALARM_STATUS_22 = None
        self.ALARM_STATUS_23 = None
        self.ALARM_STATUS_24 = None
        self.ALARM_STATUS_25 = None
        self.ALARM_STATUS_26 = None
        self.ALARM_STATUS_27 = None
        self.ALARM_STATUS_28 = None
        self.ALARM_STATUS_29 = None
        self.ALARM_STATUS_30 = None
        self.ALARM_STATUS_31 = None
        self.ALARM_STATUS_32 = None
        self.ALARM_STATUS_33 = None
        self.ALARM_STATUS_34 = None
        self.ALARM_STATUS_35 = None
        self.ALARM_STATUS_36 = None
        self.ALARM_STATUS_37 = None
        self.ALARM_STATUS_38 = None
        self.ALARM_STATUS_39 = None
        self.ALARM_STATUS_40 = None
        self.ALARM_STATUS_41 = None
        self.ALARM_STATUS_42 = None
        self.ALARM_STATUS_43 = None
        self.ALARM_STATUS_44 = None
        self.ALARM_STATUS_45 = None
        self.ALARM_STATUS_46 = None
        self.ALARM_STATUS_47 = None
        self.ALARM_STATUS_48 = None
        self.ALARM_STATUS_49 = None
        self.ALARM_STATUS_50 = None
        self.ALARM_STATUS_51 = None
        self.ALARM_STATUS_52 = None
        self.ALARM_STATUS_53 = None
        self.ALARM_STATUS_54 = None
        self.ALARM_STATUS_55 = None
        self.ALARM_STATUS_56 = None
        self.ALARM_STATUS_57 = None
        self.ALARM_STATUS_58 = None
        self.ALARM_STATUS_59 = None
        self.ALARM_STATUS_60 = None
        self.ALARM_STATUS_61 = None
        self.ALARM_STATUS_62 = None
        self.ALARM_STATUS_63 = None
        self.ALARM_STATUS_64 = None
        self.ALARM_STATUS_65 = None
        self.ALARM_STATUS_66 = None
        self.ALARM_STATUS_67 = None
        self.ALARM_STATUS_68 = None
        self.ALARM_STATUS_69 = None
        self.ALARM_STATUS_70 = None
        self.ALARM_STATUS_71 = None
        self.ALARM_STATUS_72 = None
        self.ALARM_STATUS_73 = None
        self.ALARM_STATUS_74 = None
        self.ALARM_STATUS_75 = None
        self.ALARM_STATUS_76 = None
        self.ALARM_STATUS_77 = None
        self.ALARM_STATUS_78 = None
        self.ALARM_STATUS_79 = None
        self.ALARM_STATUS_80 = None
        self.ALARM_STATUS_81 = None
        self.ALARM_STATUS_82 = None
        self.ALARM_STATUS_83 = None
        self.ALARM_STATUS_84 = None
        self.ALARM_STATUS_85 = None
        self.ALARM_STATUS_86 = None
        self.ALARM_STATUS_87 = None
        self.ALARM_STATUS_88 = None
        self.ALARM_STATUS_89 = None
        self.ALARM_STATUS_90 = None
        self.ALARM_STATUS_91 = None
        self.ALARM_STATUS_92 = None
        self.ALARM_STATUS_93 = None
        self.ALARM_STATUS_94 = None
        self.ALARM_STATUS_95 = None
        self.ALARM_STATUS_96 = None
        self.ALARM_STATUS_97 = None
        self.ALARM_STATUS_98 = None
        self.ALARM_STATUS_99 = None


    def get_agv_status(self,dmmemory:PlcMemory):
        dMMemory = dmmemory
        self.AGV_ID = dMMemory.get_string(7600, 20)
        self.POWER = dMMemory.get_float(7610, 4)
        self.AGV_X_SPEED = dMMemory.get_int(7612, 2)
        self.AGV_Y_SPEED = dMMemory.get_int(7614, 2)
        self.AGV_THETA_SPEED = dMMemory.get_int(7616, 2)
        self.AGV_FPGV = dMMemory.get_int(7618, 2)
        self.AGV_BPGV = dMMemory.get_int(7620, 2)
        self.AGV_START_POINT = dMMemory.get_int(7622, 2)
        self.AGV_END_POINT = dMMemory.get_int(7624, 2)
        self.AGV_ACTION = dMMemory.get_int(7626, 2)
        self.AGV_ZONE = dMMemory.get_int(7628, 2)
        self.AGV_SLAM_X = dMMemory.get_int(7630, 4)
        self.AGV_SLAM_Y = dMMemory.get_int(7632, 4)
        self.AGV_SLAM_THETA = dMMemory.get_int(7634, 2)
        self.AGV_STATUS1 = dMMemory.get_int(7636, 2)
        self.AGV_STATUS2 = dMMemory.get_int(7637, 2)
        self.AGV_STATUS3 = dMMemory.get_int(7638, 2)
        self.AGV_ALARM1 = dMMemory.get_int(7639, 2)
        self.AGV_ALARM2 = dMMemory.get_int(7640, 2)
        self.AGV_ALARM3 = dMMemory.get_int(7641, 2)
        self.AGV_ALARM4 = dMMemory.get_int(7642, 2)
        self.AGV_ALARM5 = dMMemory.get_int(7643, 2)
        self.AGV_ALARM6 = dMMemory.get_int(7644, 2)
        self.AGV_LAYER = dMMemory.get_int(7645, 2)
        self.AGV_ID1 = dMMemory.get_string(7650, 20)
        self.MAGIC = dMMemory.get_int(7660, 2)
        self.Req_TAGNo = dMMemory.get_int(7661, 2)
        self.Work_id = dMMemory.get_int(7662, 4)
        self.Robot_status = dMMemory.get_int(7664, 2)
        #self.Robot_take_port = dMMemory.get_int(7666, 2)
        #self.Robot_put_port = dMMemory.get_int(7668, 2)
    
 
    def get_agv_bitstatus(self,dmmemory: PlcMemory):
        d = dmmemory
        self.AGV_Auto=d.get_bit(7636,0)
        self.AGV_MOVING=d.get_bit(7636 ,1)
        self.AGV_ALARM=d.get_bit(7636,2)
        self.AGV_PATH=d.get_bit(7636,3)
        self.AGV_PATH_REQ=d.get_bit(7636,4)
        self.AGV_IN_MISSION=d.get_bit(7636, 5)
        self.AGV_LOCAL=d.get_bit(7636, 6)
        self.AGV_LD_COMPLETE=d.get_bit(7636, 7)
        self.AGV_UD_COMPLETE=d.get_bit(7636, 8)
        self.LOW_POWER=d.get_bit(7636, 9)
        self.MISSION_CANCEL=d.get_bit(7636 ,10)
        self.TRAFFIC_STOP=d.get_bit(7636 ,11)
        self.TRAFFIC_ALLOW=d.get_bit(7636 ,12)
        self.PS_RETRUN=d.get_bit(7636 ,13)
        self.AGV_MANUAL=d.get_bit(7636 ,14)
        self.AGV_2POSITION=d.get_bit(7636 ,15)
        self.IN_1=d.get_bit(7637,0)
        self.IN_2=d.get_bit(7637 ,1)
        self.IN_3=d.get_bit(7637,2)
        self.IN_4=d.get_bit(7637,3)
        self.IN_5=d.get_bit(7637,4)
        self.BARCODE_READER_FINISH=d.get_bit(7637, 5)
        self.TAG_REQ=d.get_bit(7637, 6)
        #self.Robot_cycle_finish = d.get_bit(7637, 7)
        



    def get_agv_door_open_status(self,dmmemory:PlcMemory):
        dMMemory = dmmemory
        self.DOOR_OPEN_1= dMMemory.get_bit(7638,0)
        self.DOOR_CLOSE_1= dMMemory.get_bit(7638 ,1)
        self.DOOR_OPEN_2= dMMemory.get_bit(7638,2)
        self.DOOR_CLOSE_2= dMMemory.get_bit(7638,3)
        self.DOOR_OPEN_3= dMMemory.get_bit(7638,4)
        self.DOOR_CLOSE_3= dMMemory.get_bit(7638, 5)
        self.DOOR_OPEN_4= dMMemory.get_bit(7638, 6)
        self.DOOR_CLOSE_4= dMMemory.get_bit(7638, 7)
        self.DOOR_OPEN_5= dMMemory.get_bit(7638, 8)
        self.DOOR_CLOSE_5= dMMemory.get_bit(7638, 9)
        self.DOOR_OPEN_6= dMMemory.get_bit(7638 ,10)
        self.DOOR_CLOSE_6= dMMemory.get_bit(7638 ,11)
        self.DOOR_OPEN_7= dMMemory.get_bit(7638 ,12)
        self.DOOR_CLOSE_7= dMMemory.get_bit(7638 ,13)
        self.DOOR_OPEN_8= dMMemory.get_bit(7638 ,14)
        self.DOOR_CLOSE_8= dMMemory.get_bit(7638 ,15)




    def get_agv_inputs(self,dmmemory:PlcMemory):
        dMMemory = dmmemory
        self.AGV_INPUT_1_1= dMMemory.get_bit(7670,0)
        self.AGV_INPUT_1_2= dMMemory.get_bit(7670 ,1)
        self.AGV_INPUT_1_3= dMMemory.get_bit(7670,2)
        self.AGV_INPUT_1_4= dMMemory.get_bit(7670,3)
        self.AGV_INPUT_1_5= dMMemory.get_bit(7670,4)
        self.AGV_INPUT_1_6= dMMemory.get_bit(7670 ,5)
        self.AGV_INPUT_1_7= dMMemory.get_bit(7670 ,6)
        self.AGV_INPUT_1_8= dMMemory.get_bit(7670 ,7)
        self.AGV_INPUT_1_9= dMMemory.get_bit(7670 ,8)
        self.AGV_INPUT_1_10= dMMemory.get_bit(7670 ,9)
        self.AGV_INPUT_1_11= dMMemory.get_bit(7670 ,10)
        self.AGV_INPUT_1_12= dMMemory.get_bit(7670 ,11)
        self.AGV_INPUT_1_13= dMMemory.get_bit(7670 ,12)
        self.AGV_INPUT_1_14= dMMemory.get_bit(7670 ,13)
        self.AGV_INPUT_1_15= dMMemory.get_bit(7670 ,14)
        self.AGV_INPUT_1_16= dMMemory.get_bit(7670 ,15)
        self.AGV_INPUT_2_1= dMMemory.get_bit(7671,0)
        self.AGV_INPUT_2_2= dMMemory.get_bit(7671 ,1)
        self.AGV_INPUT_2_3= dMMemory.get_bit(7671,2)
        self.AGV_INPUT_2_4= dMMemory.get_bit(7671,3)
        self.AGV_INPUT_2_5= dMMemory.get_bit(7671,4)
        self.AGV_INPUT_2_6= dMMemory.get_bit(7671 ,5)
        self.AGV_INPUT_2_7= dMMemory.get_bit(7671 ,6)
        self.AGV_INPUT_2_8= dMMemory.get_bit(7671 ,7)
        self.AGV_INPUT_2_9= dMMemory.get_bit(7671 ,8)
        self.AGV_INPUT_2_10= dMMemory.get_bit(7671 ,9)
        self.AGV_INPUT_2_11= dMMemory.get_bit(7671 ,10)
        self.AGV_INPUT_2_12= dMMemory.get_bit(7671 ,11)
        self.AGV_INPUT_2_13= dMMemory.get_bit(7671 ,12)
        self.AGV_INPUT_2_14= dMMemory.get_bit(7671 ,13)
        self.AGV_INPUT_2_15= dMMemory.get_bit(7671 ,14)
        self.AGV_INPUT_2_16= dMMemory.get_bit(7671 ,15)
        self.AGV_INPUT_3_1= dMMemory.get_bit(7672,0)
        self.AGV_INPUT_3_2= dMMemory.get_bit(7672 ,1)
        self.AGV_INPUT_3_3= dMMemory.get_bit(7672,2)
        self.AGV_INPUT_3_4= dMMemory.get_bit(7672,3)
        self.AGV_INPUT_3_5= dMMemory.get_bit(7672,4)
        self.AGV_INPUT_3_6= dMMemory.get_bit(7672 ,5)
        self.AGV_INPUT_3_7= dMMemory.get_bit(7672 ,6)
        self.AGV_INPUT_3_8= dMMemory.get_bit(7672 ,7)
        self.AGV_INPUT_3_9= dMMemory.get_bit(7672 ,8)
        self.AGV_INPUT_3_10= dMMemory.get_bit(7672 ,9)
        self.AGV_INPUT_3_11= dMMemory.get_bit(7672 ,10)
        self.AGV_INPUT_3_12= dMMemory.get_bit(7672 ,11)
        self.AGV_INPUT_3_13= dMMemory.get_bit(7672 ,12)
        self.AGV_INPUT_3_14= dMMemory.get_bit(7672 ,13)
        self.AGV_INPUT_3_15= dMMemory.get_bit(7672 ,14)
        self.AGV_INPUT_3_16= dMMemory.get_bit(7672 ,15)
        self.AGV_INPUT_4_1= dMMemory.get_bit(7673,0)
        self.AGV_INPUT_4_2= dMMemory.get_bit(7673 ,1)
        self.AGV_INPUT_4_3= dMMemory.get_bit(7673,2)
        self.AGV_INPUT_4_4= dMMemory.get_bit(7673,3)
        self.AGV_INPUT_4_5= dMMemory.get_bit(7673,4)
        self.AGV_INPUT_4_6= dMMemory.get_bit(7673 ,5)
        self.AGV_INPUT_4_7= dMMemory.get_bit(7673 ,6)
        self.AGV_INPUT_4_8= dMMemory.get_bit(7673 ,7)
        self.AGV_INPUT_4_9= dMMemory.get_bit(7673 ,8)
        self.AGV_INPUT_4_10= dMMemory.get_bit(7673 ,9)
        self.AGV_INPUT_4_11= dMMemory.get_bit(7673 ,10)
        self.AGV_INPUT_4_12= dMMemory.get_bit(7673 ,11)
        self.AGV_INPUT_4_13= dMMemory.get_bit(7673 ,12)
        self.AGV_INPUT_4_14= dMMemory.get_bit(7673 ,13)
        self.AGV_INPUT_4_15= dMMemory.get_bit(7673 ,14)
        self.AGV_INPUT_4_16= dMMemory.get_bit(7673 ,15)
        self.AGV_INPUT_5_1= dMMemory.get_bit(7674,0)
        self.AGV_INPUT_5_2= dMMemory.get_bit(7674 ,1)
        self.AGV_INPUT_5_3= dMMemory.get_bit(7674,2)
        self.AGV_INPUT_5_4= dMMemory.get_bit(7674,3)
        self.AGV_INPUT_5_5= dMMemory.get_bit(7674,4)
        self.AGV_INPUT_5_6= dMMemory.get_bit(7674 ,5)
        self.AGV_INPUT_5_7= dMMemory.get_bit(7674 ,6)
        self.AGV_INPUT_5_8= dMMemory.get_bit(7674 ,7)
        self.AGV_INPUT_5_9= dMMemory.get_bit(7674 ,8)
        self.AGV_INPUT_5_10= dMMemory.get_bit(7674 ,9)
        self.AGV_INPUT_5_11= dMMemory.get_bit(7674 ,10)
        self.AGV_INPUT_5_12= dMMemory.get_bit(7674 ,11)
        self.AGV_INPUT_5_13= dMMemory.get_bit(7674 ,12)
        self.AGV_INPUT_5_14= dMMemory.get_bit(7674 ,13)
        self.AGV_INPUT_5_15= dMMemory.get_bit(7674 ,14)
        self.AGV_INPUT_5_16= dMMemory.get_bit(7674 ,15)        



    def get_agv_outputs(self,dmmemory:PlcMemory):
        dMMemory = dmmemory
        self.AGV_OUTPUT_1_1= dMMemory.get_bit(7675,0)
        self.AGV_OUTPUT_1_2= dMMemory.get_bit(7675 ,1)
        self.AGV_OUTPUT_1_3= dMMemory.get_bit(7675,2)
        self.AGV_OUTPUT_1_4= dMMemory.get_bit(7675,3)
        self.AGV_OUTPUT_1_5= dMMemory.get_bit(7675,4)
        self.AGV_OUTPUT_1_6= dMMemory.get_bit(7675 ,5)
        self.AGV_OUTPUT_1_7= dMMemory.get_bit(7675 ,6)
        self.AGV_OUTPUT_1_8= dMMemory.get_bit(7675 ,7)
        self.AGV_OUTPUT_1_9= dMMemory.get_bit(7675 ,8)
        self.AGV_OUTPUT_1_10= dMMemory.get_bit(7675 ,9)
        self.AGV_OUTPUT_1_11= dMMemory.get_bit(7675 ,10)
        self.AGV_OUTPUT_1_12= dMMemory.get_bit(7675 ,11)
        self.AGV_OUTPUT_1_13= dMMemory.get_bit(7675 ,12)
        self.AGV_OUTPUT_1_14= dMMemory.get_bit(7675 ,13)
        self.AGV_OUTPUT_1_15= dMMemory.get_bit(7675 ,14)
        self.AGV_OUTPUT_1_16= dMMemory.get_bit(7675 ,15)
        self.AGV_OUTPUT_2_1= dMMemory.get_bit(7676,0)
        self.AGV_OUTPUT_2_2= dMMemory.get_bit(7676 ,1)
        self.AGV_OUTPUT_2_3= dMMemory.get_bit(7676,2)
        self.AGV_OUTPUT_2_4= dMMemory.get_bit(7676,3)
        self.AGV_OUTPUT_2_5= dMMemory.get_bit(7676,4)
        self.AGV_OUTPUT_2_6= dMMemory.get_bit(7676 ,5)
        self.AGV_OUTPUT_2_7= dMMemory.get_bit(7676 ,6)
        self.AGV_OUTPUT_2_8= dMMemory.get_bit(7676 ,7)
        self.AGV_OUTPUT_2_9= dMMemory.get_bit(7676 ,8)
        self.AGV_OUTPUT_2_10= dMMemory.get_bit(7676 ,9)
        self.AGV_OUTPUT_2_11= dMMemory.get_bit(7676 ,10)
        self.AGV_OUTPUT_2_12= dMMemory.get_bit(7676 ,11)
        self.AGV_OUTPUT_2_13= dMMemory.get_bit(7676 ,12)
        self.AGV_OUTPUT_2_14= dMMemory.get_bit(7676 ,13)
        self.AGV_OUTPUT_2_15= dMMemory.get_bit(7676 ,14)
        self.AGV_OUTPUT_2_16= dMMemory.get_bit(7676 ,15)
        self.AGV_OUTPUT_3_1= dMMemory.get_bit(7677,0)
        self.AGV_OUTPUT_3_2= dMMemory.get_bit(7677 ,1)
        self.AGV_OUTPUT_3_3= dMMemory.get_bit(7677,2)
        self.AGV_OUTPUT_3_4= dMMemory.get_bit(7677,3)
        self.AGV_OUTPUT_3_5= dMMemory.get_bit(7677,4)
        self.AGV_OUTPUT_3_6= dMMemory.get_bit(7677 ,5)
        self.AGV_OUTPUT_3_7= dMMemory.get_bit(7677 ,6)
        self.AGV_OUTPUT_3_8= dMMemory.get_bit(7677 ,7)
        self.AGV_OUTPUT_3_9= dMMemory.get_bit(7677 ,8)
        self.AGV_OUTPUT_3_10= dMMemory.get_bit(7677 ,9)
        self.AGV_OUTPUT_3_11= dMMemory.get_bit(7677 ,10)
        self.AGV_OUTPUT_3_12= dMMemory.get_bit(7677 ,11)
        self.AGV_OUTPUT_3_13= dMMemory.get_bit(7677 ,12)
        self.AGV_OUTPUT_3_14= dMMemory.get_bit(7677 ,13)
        self.AGV_OUTPUT_3_15= dMMemory.get_bit(7677 ,14)
        self.AGV_OUTPUT_3_16= dMMemory.get_bit(7677 ,15)
        self.AGV_OUTPUT_4_1= dMMemory.get_bit(7678,0)
        self.AGV_OUTPUT_4_2= dMMemory.get_bit(7678 ,1)
        self.AGV_OUTPUT_4_3= dMMemory.get_bit(7678,2)
        self.AGV_OUTPUT_4_4= dMMemory.get_bit(7678,3)
        self.AGV_OUTPUT_4_5= dMMemory.get_bit(7678,4)
        self.AGV_OUTPUT_4_6= dMMemory.get_bit(7678 ,5)
        self.AGV_OUTPUT_4_7= dMMemory.get_bit(7678 ,6)
        self.AGV_OUTPUT_4_8= dMMemory.get_bit(7678 ,7)
        self.AGV_OUTPUT_4_9= dMMemory.get_bit(7678 ,8)
        self.AGV_OUTPUT_4_10= dMMemory.get_bit(7678 ,9)
        self.AGV_OUTPUT_4_11= dMMemory.get_bit(7678 ,10)
        self.AGV_OUTPUT_4_12= dMMemory.get_bit(7678 ,11)
        self.AGV_OUTPUT_4_13= dMMemory.get_bit(7678 ,12)
        self.AGV_OUTPUT_4_14= dMMemory.get_bit(7678 ,13)
        self.AGV_OUTPUT_4_15= dMMemory.get_bit(7678 ,14)
        self.AGV_OUTPUT_4_16= dMMemory.get_bit(7678 ,15)
        self.AGV_OUTPUT_5_1= dMMemory.get_bit(7679,0)
        self.AGV_OUTPUT_5_2= dMMemory.get_bit(7679 ,1)
        self.AGV_OUTPUT_5_3= dMMemory.get_bit(7679,2)
        self.AGV_OUTPUT_5_4= dMMemory.get_bit(7679,3)
        self.AGV_OUTPUT_5_5= dMMemory.get_bit(7679,4)
        self.AGV_OUTPUT_5_6= dMMemory.get_bit(7679 ,5)
        self.AGV_OUTPUT_5_7= dMMemory.get_bit(7679 ,6)
        self.AGV_OUTPUT_5_8= dMMemory.get_bit(7679 ,7)
        self.AGV_OUTPUT_5_9= dMMemory.get_bit(7679 ,8)
        self.AGV_OUTPUT_5_10= dMMemory.get_bit(7679 ,9)
        self.AGV_OUTPUT_5_11= dMMemory.get_bit(7679 ,10)
        self.AGV_OUTPUT_5_12= dMMemory.get_bit(7679 ,11)
        self.AGV_OUTPUT_5_13= dMMemory.get_bit(7679 ,12)
        self.AGV_OUTPUT_5_14= dMMemory.get_bit(7679 ,13)
        self.AGV_OUTPUT_5_15= dMMemory.get_bit(7679 ,14)
        self.AGV_OUTPUT_5_16= dMMemory.get_bit(7679 ,15)             




    def get_alarm_status(self,dmmemory:PlcMemory):
        dMMemory = dmmemory
        self.ALARM_STATUS_1= dMMemory.get_bit(7639 ,0)
        self.ALARM_STATUS_2= dMMemory.get_bit(7639 ,1)
        self.ALARM_STATUS_3= dMMemory.get_bit(7639 ,2)
        self.ALARM_STATUS_4= dMMemory.get_bit(7639 ,3)
        self.ALARM_STATUS_5= dMMemory.get_bit(7639 ,4)
        self.ALARM_STATUS_6= dMMemory.get_bit(7639 ,5)
        self.ALARM_STATUS_7= dMMemory.get_bit(7639 ,6)
        self.ALARM_STATUS_8= dMMemory.get_bit(7639 ,7)
        self.ALARM_STATUS_9= dMMemory.get_bit(7639 ,8)
        self.ALARM_STATUS_10= dMMemory.get_bit(7639 ,9)
        self.ALARM_STATUS_11= dMMemory.get_bit(7639 ,10)
        self.ALARM_STATUS_12= dMMemory.get_bit(7639 ,11)
        self.ALARM_STATUS_13= dMMemory.get_bit(7639 ,12)
        self.ALARM_STATUS_14= dMMemory.get_bit(7639 ,13)
        self.ALARM_STATUS_15= dMMemory.get_bit(7639 ,14)
        self.ALARM_STATUS_16= dMMemory.get_bit(7639 ,15)
        self.ALARM_STATUS_17= dMMemory.get_bit(7640 ,0)
        self.ALARM_STATUS_18= dMMemory.get_bit(7640 ,1)
        self.ALARM_STATUS_19= dMMemory.get_bit(7640 ,2)
        self.ALARM_STATUS_20= dMMemory.get_bit(7640 ,3)
        self.ALARM_STATUS_21= dMMemory.get_bit(7640 ,4)
        self.ALARM_STATUS_22= dMMemory.get_bit(7640 ,5)
        self.ALARM_STATUS_23= dMMemory.get_bit(7640 ,6)
        self.ALARM_STATUS_24= dMMemory.get_bit(7640 ,7)
        self.ALARM_STATUS_25= dMMemory.get_bit(7640 ,8)
        self.ALARM_STATUS_26= dMMemory.get_bit(7640 ,9)
        self.ALARM_STATUS_27= dMMemory.get_bit(7640 ,10)
        self.ALARM_STATUS_28= dMMemory.get_bit(7640 ,11)
        self.ALARM_STATUS_29= dMMemory.get_bit(7640 ,12)
        self.ALARM_STATUS_30= dMMemory.get_bit(7640 ,13)
        self.ALARM_STATUS_31= dMMemory.get_bit(7640 ,14)
        self.ALARM_STATUS_32= dMMemory.get_bit(7640 ,15)
        self.ALARM_STATUS_33= dMMemory.get_bit(7641 ,0)
        self.ALARM_STATUS_34= dMMemory.get_bit(7641 ,1)
        self.ALARM_STATUS_35= dMMemory.get_bit(7641 ,2)
        self.ALARM_STATUS_36= dMMemory.get_bit(7641 ,3)
        self.ALARM_STATUS_37= dMMemory.get_bit(7641 ,4)
        self.ALARM_STATUS_38= dMMemory.get_bit(7641 ,5)
        self.ALARM_STATUS_39= dMMemory.get_bit(7641 ,6)
        self.ALARM_STATUS_40= dMMemory.get_bit(7641 ,7)
        self.ALARM_STATUS_41= dMMemory.get_bit(7641 ,8)
        self.ALARM_STATUS_42= dMMemory.get_bit(7641 ,9)
        self.ALARM_STATUS_43= dMMemory.get_bit(7641 ,10)
        self.ALARM_STATUS_44= dMMemory.get_bit(7641 ,11)
        self.ALARM_STATUS_45= dMMemory.get_bit(7641 ,12)
        self.ALARM_STATUS_46= dMMemory.get_bit(7641 ,13)
        self.ALARM_STATUS_47= dMMemory.get_bit(7641 ,14)
        self.ALARM_STATUS_48= dMMemory.get_bit(7641 ,15)
        self.ALARM_STATUS_49= dMMemory.get_bit(7642 ,0)
        self.ALARM_STATUS_50= dMMemory.get_bit(7642 ,1)
        self.ALARM_STATUS_51= dMMemory.get_bit(7642 ,2)
        self.ALARM_STATUS_52= dMMemory.get_bit(7642 ,3)
        self.ALARM_STATUS_53= dMMemory.get_bit(7642 ,4)
        self.ALARM_STATUS_54= dMMemory.get_bit(7642 ,5)
        self.ALARM_STATUS_55= dMMemory.get_bit(7642 ,6)
        self.ALARM_STATUS_56= dMMemory.get_bit(7642 ,7)
        self.ALARM_STATUS_57= dMMemory.get_bit(7642 ,8)
        self.ALARM_STATUS_58= dMMemory.get_bit(7642 ,9)
        self.ALARM_STATUS_59= dMMemory.get_bit(7642 ,10)
        self.ALARM_STATUS_60= dMMemory.get_bit(7642 ,11)
        self.ALARM_STATUS_61= dMMemory.get_bit(7642 ,12)
        self.ALARM_STATUS_62= dMMemory.get_bit(7642 ,13)
        self.ALARM_STATUS_63= dMMemory.get_bit(7642 ,14)
        self.ALARM_STATUS_64= dMMemory.get_bit(7642 ,15)
        self.ALARM_STATUS_65= dMMemory.get_bit(7643 ,0)
        self.ALARM_STATUS_66= dMMemory.get_bit(7643 ,1)
        self.ALARM_STATUS_67= dMMemory.get_bit(7643 ,2)
        self.ALARM_STATUS_68= dMMemory.get_bit(7643 ,3)
        self.ALARM_STATUS_69= dMMemory.get_bit(7643 ,4)
        self.ALARM_STATUS_70= dMMemory.get_bit(7643 ,5)
        self.ALARM_STATUS_71= dMMemory.get_bit(7643 ,6)
        self.ALARM_STATUS_72= dMMemory.get_bit(7643 ,7)
        self.ALARM_STATUS_73= dMMemory.get_bit(7643 ,8)
        self.ALARM_STATUS_74= dMMemory.get_bit(7643 ,9)
        self.ALARM_STATUS_75= dMMemory.get_bit(7643 ,10)
        self.ALARM_STATUS_76= dMMemory.get_bit(7643 ,11)
        self.ALARM_STATUS_77= dMMemory.get_bit(7643 ,12)
        self.ALARM_STATUS_78= dMMemory.get_bit(7643 ,13)
        self.ALARM_STATUS_79= dMMemory.get_bit(7643 ,14)
        self.ALARM_STATUS_80= dMMemory.get_bit(7643 ,15)
        self.ALARM_STATUS_81= dMMemory.get_bit(7644 ,0)
        self.ALARM_STATUS_82= dMMemory.get_bit(7644 ,1)
        self.ALARM_STATUS_83= dMMemory.get_bit(7644 ,2)
        self.ALARM_STATUS_84= dMMemory.get_bit(7644 ,3)
        self.ALARM_STATUS_85= dMMemory.get_bit(7644 ,4)
        self.ALARM_STATUS_86= dMMemory.get_bit(7644 ,5)
        self.ALARM_STATUS_87= dMMemory.get_bit(7644 ,6)
        self.ALARM_STATUS_88= dMMemory.get_bit(7644 ,7)
        self.ALARM_STATUS_89= dMMemory.get_bit(7644 ,8)
        self.ALARM_STATUS_90= dMMemory.get_bit(7644 ,9)
        self.ALARM_STATUS_91= dMMemory.get_bit(7644 ,10)
        self.ALARM_STATUS_92= dMMemory.get_bit(7644 ,11)
        self.ALARM_STATUS_93= dMMemory.get_bit(7644 ,12)
        self.ALARM_STATUS_94= dMMemory.get_bit(7644 ,13)
        self.ALARM_STATUS_95= dMMemory.get_bit(7644 ,14)
        self.ALARM_STATUS_96= dMMemory.get_bit(7644 ,15)


