
# AGV 狀態訊息，對應 agv_node_base.py 的 publish_agv_status 欄位
string agv_id
float64 slam_x
float64 slam_y
float64 slam_theta
float64 power
float64 x_speed
float64 y_speed
float64 theta_speed
int32 front_pgv
int32 back_pgv
int32 start_point
int32 end_point
int32 action
int32 zone
int32 status1
int32 status2
int32 status3
int32 alarm1
int32 alarm2
int32 alarm3
int32 alarm4
int32 alarm5
int32 alarm6
int32 magic
int32 layer
